# Generated by Django 2.2.4 on 2023-11-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time']},
        ),
    ]
