# Generated by Django 2.2.4 on 2023-11-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20231124_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
